# Generated by Django 3.2.18 on 2023-04-24 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0004_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlib',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='userlib',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userlib',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messenger.books', verbose_name='Книги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlib',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
