# Generated by Django 3.2.18 on 2023-04-25 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0005_auto_20230424_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='StarList',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book_slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='book_URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserLib',
        ),
    ]
